## Ejercicio de Clustering, Regression y Clasificacion

Continuación del ejercicio anterior:

Ya tenemos los modelos de regresión lineal para ambas nubes. Si quisieramos predecir una nueva instancia tendriamos que transformar esa nueva "fila" para que tenga el mismo "formato" que las filas que usamos para crear los modelos, es decir, hay que aplicar el mismo preprocesamiento para poder utilizar esa instancia con el modelo:

**Parte 1**:
1. Define una función que tome como parametro una instancia o una lista de instancias y que aplique el mismo preprocesamiento a esa instancia o lista de instancias.
2. Esta función debe usar el mismo escalador, aplicar las mismas transformaciones y crear las mismas columnas que las realizadas en el preprocesamiento.
3. La función debe retornar una instancia unica o una lista de instancias ya preprocesadas.
4. Estas instancias no tendran la columna de **`CO2EMISSIONS`**.

**Parte 2**:

Ahora tenemos que "clasificar" las nuevas instancias para saber con cual modelo de regresión vamos a hacer la prediccion:

1. Utilizando el dataset preprocesado de **`FuelConsumptionCo2.csv`**, vamos a realizar un modelo de clasificación para predecir la columna generada por el **`cluster`**. Es decir, el dataset para este modelo debe tener todas las columnas a excepción de **`CO2EMISSIONS`** y vamos a intentar predecir la columna **`cluster`**.

2. Define una función que tome como parámetro una instancia o lista de instancias **SIN PREPROCESAR** y que haga lo siguiente:
    - Aplique el preprocesamiento (la función definida en la **Parte 1**).
    - Utilice el modelo de clasificación para decidir que modelo de regresión aplicar.
    - Dependiendo del caso, que haga la predicción del modelo de regresión a cada instancia.
    - **Debe retornar una lista de predicciones del modelo de regresión**, recuerda desescalar los datos predichos.

In [131]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

"MODELYEAR","MODEL"

In [132]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# Normalizacion
from sklearn.preprocessing import MinMaxScaler
import pickle

# Parte 1

In [135]:
csv = 'FuelConsumptionCo2.csv'
csv= 'Fuel1.csv'
def prepro_clasificar(csv):
    
    df = pd.read_csv(csv)
  
    ## Tratamiento df_num
    
    df_num = df._get_numeric_data().copy()

    df_num["ENGINESIZE"] = df_num["ENGINESIZE"].apply(lambda x: 0 if x < 4 else 1)
    df_num["CYLINDERS"] = df_num["CYLINDERS"].apply(lambda x: 0 if x < 8 else 1)
    df_num["FUELCONSUMPTION_COMB_MPG"] = df_num["FUELCONSUMPTION_COMB_MPG"].apply(lambda x: x**-1)

    
    ## Tratamiento df_cat
    df_cat = df.drop(df_num.columns, axis = 1)
    df_cat = pd.concat([df_cat, pd.get_dummies(data = df_cat["MAKE"])], axis = 1)
    df_cat = pd.concat([df_cat, pd.get_dummies(data = df_cat["VEHICLECLASS"])], axis = 1)
    df_cat["TRANSMISSION"] = df_cat["TRANSMISSION"].replace({"AS5" : "Automático", "M6" : "Manual",
                                                         "AV7" : "Automático", "AM7" : "Automático",
                                                         "AS6" : "Automático", "A6" : "Automático",
                                                         "AV8" : "Automático", "AS8" : "Automático",
                                                         "A7" : "Automático", "A8" : "Automático",
                                                         "M7" : "Manual", "M5" : "Manual", 
                                                         "A4" : "Automático", "AV" : "Automático",
                                                         "A5" : "Automático", "AM6" : "Automático",
                                                         "AS7" : "Automático", "A9" : "Automático",
                                                         "AS9" : "Automático", "AV6" : "Automático",
                                                         "AS4" : "Automático", "AM5" : "Automático"})
    df_cat = pd.concat([df_cat, pd.get_dummies(data = df_cat["TRANSMISSION"])], axis = 1)
    df_cat = pd.concat([df_cat, pd.get_dummies(data = df_cat["FUELTYPE"])], axis = 1)
    
    for col in ["MAKE", "MODEL","VEHICLECLASS", "TRANSMISSION", "FUELTYPE"]:
        df_cat.drop(col, axis = 1, inplace = True)
        
    ## Concatenar df_cat y df_num
    
    df = pd.concat([df_num, df_cat], axis = 1)
    df = df.drop(['MODELYEAR'], axis = 1)

    columnas = ['ENGINESIZE', 'CYLINDERS', 'FUELCONSUMPTION_CITY',
   'FUELCONSUMPTION_HWY', 'FUELCONSUMPTION_COMB',
   'FUELCONSUMPTION_COMB_MPG', 'CO2EMISSIONS', 'ACURA', 'ASTON MARTIN',
   'AUDI', 'BENTLEY', 'BMW', 'BUICK', 'CADILLAC', 'CHEVROLET', 'CHRYSLER',
   'DODGE', 'FIAT', 'FORD', 'GMC', 'HONDA', 'HYUNDAI', 'INFINITI',
   'JAGUAR', 'JEEP', 'KIA', 'LAMBORGHINI', 'LAND ROVER', 'LEXUS',
   'LINCOLN', 'MASERATI', 'MAZDA', 'MERCEDES-BENZ', 'MINI', 'MITSUBISHI',
   'NISSAN', 'PORSCHE', 'RAM', 'ROLLS-ROYCE', 'SCION', 'SMART', 'SRT',
   'SUBARU', 'TOYOTA', 'VOLKSWAGEN', 'VOLVO', 'COMPACT', 'FULL-SIZE',
   'MID-SIZE', 'MINICOMPACT', 'MINIVAN', 'PICKUP TRUCK - SMALL',
   'PICKUP TRUCK - STANDARD', 'SPECIAL PURPOSE VEHICLE',
   'STATION WAGON - MID-SIZE', 'STATION WAGON - SMALL', 'SUBCOMPACT',
   'SUV - SMALL', 'SUV - STANDARD', 'TWO-SEATER', 'VAN - CARGO',
   'VAN - PASSENGER', 'Automático', 'Manual', 'D', 'E', 'X', 'Z']
    
    df_patron = pd.DataFrame(columns= columnas)
    
    df = pd.concat([df_patron, df]).fillna(0)
    
    X = df
    
    with open("escalador", "br") as file:
        x_scaler = pickle.load(file)
        
    X = x_scaler.transform(X)
    
    df_x = pd.DataFrame(X, columns=df.columns)
    
    return df_x

In [136]:
prepro_clasificar(csv)

,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS,ACURA,ASTON MARTIN,AUDI,...,SUV - STANDARD,TWO-SEATER,VAN - CARGO,VAN - PASSENGER,Automático,Manual,D,E,X,Z
0,0.0,0.0,0.207031,0.115385,0.180095,0.183673,0.231579,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

# Parte 2

In [139]:
df = pd.read_csv('Fuelpreprocesado_Grupo0.csv')
df

,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS,ACURA,ASTON MARTIN,AUDI,...,TWO-SEATER,VAN - CARGO,VAN - PASSENGER,Automático,Manual,D,E,X,Z,Clases
0,0,0,9.9,6.7,8.5,0.030303,196,1,0,0,...,0,0,0,1,0,0,0,0,1,0
1,0,0,11.2,7.7,9.6,0.034483,221,1,0,0,...,0,0,0,0,1,0,0,0,1,0
2,0,0,6.0,5.8,5.9,0.020833,136,1,0,0,...,0,0,0,1,0,0,0,0,1,0
3,0,0,12.7,9.1,11.1,0.040000,255,1,0,0,...,0,0,0,1,0,0,0,0,1,0
4,0,0,12.1,8.7,10.6,0.037037,244,1,0,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,0,0,13.4,9.8,11.8,0.041667,271,0,0,0,...,0,0,0,1,0,0,0,1,0,0
1063,0,0,13.2,9.5,11.5,0.040000,264,0,0,0,...,0,0,0,1,0,0,0,1,0,0
1064,0,0,13.4,9.8,11.8,0.041667,271,0,0,0,...,0,0,0,1,0,0,0,1,0,0
1065,0,0,12.9,9.3,11.3,0.040000,260,0,0,0,...,0,0,0,1,0,0,0,1,0,0
1066,0,0,14.9,10.2,12.8,0.045455,294,0,0,0,...,0,0,0,1,0,0,0,1,0,0

In [140]:
df.drop("CO2EMISSIONS", axis = 1, inplace = True)